apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: yihengchen-me-tls
spec:
  secretName: yihengchen-me
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: chenyiheng.me
  dnsNames:
    - chenyiheng.me
    - www.chenyiheng.me
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - chenyiheng.me
          - www.chenyiheng.me